### ISSUE TITLE
Cleanup required

### ISSUE THREAD

**Issue by jeromekelleher** [mcveanlab/treeseq-inference#51] opened 2018-09-20 13:15 UTC
As we're converging on publication, we should tidy things up so that others will be able to follow what we've done and reproduce it. 

1. Move tools we are using (ArgWeaver etc) into a directory called 'tools', and update paths accordingly.
2. Delete any submodules we're not using (icytree, ftprime_ms ...)
3. Delete msprime and tsinfer submodules. In practise it's much more robust to put a required version in to the code: we can insist on msprime version == 0.6.2 and tsinfer == 0.1.3. (For now we can install from git to run the analyses)
4. Delete any code we're not using

The goal here is to make the simplest and cleanest repo that we can that would allow someone else to reproduce the plots in the paper **exactly**. If we want to keep code for other purposes we can make a copy of the repo. Once the paper is published this repo will be frozen.

How does this sound @hyanwong?

**Comment by jeromekelleher** [comment] 2018-09-27 09:48
It's looking great, thanks @hyanwong. I think  there's a few more things we can clean up, and we can close this issue then:

- Does the 'visualisations' directory do anything? I can't see us using this for the paper
- Likewise for the 'tests' directory. Having a quick scan through it, most of the stuff in there is out of date and probably doesn't run. I don't think there's much point in having test cases here, so I would delete it.

**Comment by hyanwong** [comment] 2018-09-27 10:05
Good point about 'visualisations' - I had forgotten I made that. I will delete it. Happy to kill `tests` too - I think that's mostly your code. Do you want to delete or shall I?

**Comment by hyanwong** [comment] 2018-09-27 14:15
I also see that at the top level there is a file called `ts_extras.txt` which seems to be a more recent near-duplicate of src/ts_extras.py, so I've unified them and am testing now.

**Closed as completed** 2018-10-15 16:24 UTC
